services:
  - type: web
    name: ztm-data-api
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: SOCCERDATA_DIR
        value: /tmp/soccerdata_cache
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
